import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/app/**/*.{ts,tsx}",
    "./src/lib/**/*.{ts,tsx}",
    "./src/hooks/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#380d00",
        "on-tertiary-fixed-variant": "#802a00",
        "on-primary-fixed": "#00174d",
        tertiary: "#852b00",
        "tertiary-container": "#ad3b00",
        secondary: "#4b5c92",
        "on-background": "#191c1e",
        "on-surface-variant": "#434654",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dadc",
        "primary-fixed": "#dbe1ff",
        outline: "#737686",
        "primary-fixed-dim": "#b5c4ff",
        "on-secondary-fixed-variant": "#334479",
        "inverse-on-surface": "#f0f1f3",
        "surface-container-low": "#f3f4f6",
        "surface-container": "#edeef0",
        "inverse-primary": "#b5c4ff",
        "surface-container-highest": "#e1e2e4",
        "on-primary-fixed-variant": "#003dab",
        "on-tertiary-container": "#ffd4c5",
        "inverse-surface": "#2e3132",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#b5c4ff",
        "on-secondary-container": "#3d4e84",
        "secondary-container": "#b1c2ff",
        "primary-container": "#1a56db",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8ea",
        background: "var(--background)",
        foreground: "var(--foreground)",
        "on-primary-container": "#d4dcff",
        "secondary-fixed": "#dbe1ff",
        "on-surface": "#191c1e",
        "surface-tint": "#1353d8",
        error: "#ba1a1a",
        "on-secondary-fixed": "#01174b",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        surface: "#f8f9fb",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdbcf",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb59a",
        "on-error-container": "#93000a",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.375rem",
        xl: "0.5rem",
        full: "9999px",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
